### ISSUE TITLE
Any chance for CDN?

### ISSUE THREAD

**Issue by Khdoop** [lazarljubenovic/grassy#5]
Would be nicer and easier to play with in codepen, plnkr, etc.

**Comment by dbox** [comment]
@khdoop I made a quick codepen playground here: 

http://codepen.io/dbox/pen/aJLGxE

But going fwd CDN would be good for keeping it updatwed automatically.

**Comment by lazarljubenovic** [comment]
I've never created a CDN before :sweat_smile: The idea is to keep a generated bundle with all partials as a single file, and then use something like [RawGit](http://rawgit.com/) to access it, right?

**Comment by dbox** [comment]
You should definitely keep it as partials for the main repo, but maybe you can use a build system to merge all the files into one `.scss` file that could be served via the CDN.

```
cat subfolder/file.scss subfolder/file2.scss file.css file2.scss >> grassy_concat.scss
```

**Comment by lazarljubenovic** [comment]
Added by 73de9ea4f014341d4503b186a0238960e17ef8fe.

You can use the latest master branch with (for example) https://rawgit.com/lazarljubenovic/grassy/master/bundle.scss.
