### ISSUE TITLE
IE9+ support?

### ISSUE THREAD

**Issue by sormy** [lazarljubenovic/grassy#7]
I see that calc is used (IE11+), do you have a plans to fix it?

**Comment by lazarljubenovic** [comment]
I don't have an IE to test it on. According to caniuse, IE9 supports calc but crashes when used on `background-position`. If this is correct, then the calc part should work. If it falls apart, it's because of flexbox.

Anyway, I doubt `calc`s can go away.

**Comment by sormy** [comment]
ok
